services:
  postgres:
    image: postgres:16
    container_name: workafella-postgres
    environment:
      POSTGRES_DB: workafella_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - workafella_pg:/var/lib/postgresql/data

volumes:
  workafella_pg:
